#!/usr/bin/env bash

#MISE hide=true
#MISE quiet=true
#MISE depends=['build:release', 'render:posts']
#MISE wait_for=['clean']
#MISE sources=['content/posts/**/*.md']
#MISE outputs=['generated/posts/index/*']

mkdir -p generated/posts/index

./target/release/lyre
