[workspace]

members = ["lyre"]

[package]
name = "orpheus"
version = "0.1.0"
edition = "2021"
include = ["generated", "content", "web"]

[dependencies]
axum = { version = "0.7.5", features = ["macros"] }
http-body-util = "0.1.1"
maud = { version = "0.26.0", features = ["axum"] }
serde = { version = "1.0.197" }
serde_yaml = "0.9.34"
shuttle-axum = "0.45.0"
shuttle-runtime = { version = "0.45.0" }
tokio = "1.28.2"
tower-http = { version = "0.5.2", features = [
    "fs",
    "trace",
    "compression-br",
    "compression-deflate",
    "compression-gzip",
    "compression-zstd",
] }
tower-livereload = "0.9.2"
lyre = { path = "./lyre" }
tower = "0.4.13"
axum-htmx = { version = "0.5.0", features = ["serde"] }
axum-extra = { version = "0.9.3", features = ["query"] }
tracing = "0.1.40"
thiserror = "1.0.59"
serde_html_form = "0.2.6"
serde_json = "1.0.116"

[build-dependencies]
lyre = { path = "./lyre" }
