[tools]
node = "24.2.0"
pandoc = "3.7.0.2"
rust = "1.87.0"
watchexec = "2.3.2"
"npm:@catppuccin/palette" = "1.7.1"
"npm:@picocss/pico" = "2.0.6"
"npm:htmx-ext-head-support" = "2.0.4"
"npm:htmx-ext-preload" = "2.1.1"
"npm:htmx.org" = "2.0.5"

[env]
'_'.file = "secrets.env"

[tasks.'build:lyre']
quiet = true
hide = true
sources = ['Cargo.lock', 'lyre/Cargo.toml', 'lyre/src/**/*.rs']
outputs = ['target/debug/lyre']
run = 'cargo build -p lyre'

[tasks.'build:lyre:release']
quiet = true
hide = true
sources = ['Cargo.lock', 'lyre/Cargo.toml', 'lyre/src/**/*.rs']
outputs = ['target/release/lyre']
run = 'cargo build -p lyre --release'

[tasks.'build:orpheus']
quiet = true
hide = true
sources = ['Cargo.lock', 'orpheus/Cargo.toml', 'orpheus/src/**/*.rs']
outputs = ['target/debug/orpheus']
run = 'cargo build -p orpheus'

[tasks.'build:orpheus:release']
quiet = true
hide = true
sources = ['Cargo.lock', 'orpheus/Cargo.toml', 'orpheus/src/**/*.rs']
outputs = ['target/release/orpheus']
run = 'cargo build -p orpheus --release'

[tasks.clean]
description = "delete generated static content"
run = 'rm -r generated'

[tasks.lyre]
quiet = true
hide = true
depends = ['build:lyre:release']
sources = ['content/**/*', 'node_modules/**/*']
outputs = ['generated/**/*']
run = './target/release/lyre build'

[tasks.orpheus]
hide = true
quiet = true
depends = ['build:orpheus:release']
wait_for = ['lyre']
run = './target/release/orpheus'

[tasks.new-post]
quiet = true
description = "generate a new post from a template"
depends = ['build:lyre:release']
run = './target/release/lyre gen'

[tasks.dev]
quiet = true
description = "run in debug mode"
depends = ['build:lyre', 'build:orpheus']
run = '''
./target/debug/lyre build
ORPHEUS_OPTIONS="live_reload,no_cache,simulate_lag" ./target/debug/orpheus
'''

[tasks.default]
quiet = true
description = "run in release mode"
depends = ['build:lyre:release', 'build:orpheus:release']
run = '''
./target/release/lyre build
ORPHEUS_OPTIONS="live_reload,no_cache" ./target/release/orpheus
'''

[tasks.author]
quiet = true
description = "run a hot-reloading server in release mode"
depends = ['build:lyre:release', 'build:orpheus:release']
run = 'ORPHEUS_OPTIONS="live_reload,no_cache" mise watch -r lyre ::: orpheus'

[tasks.update]
quiet = true
description = "deploy latest code changes"
run = '''
ssh $ORPHEUS_HOST $ORPHEUS_UPDATE
ssh $ORPHEUS_HOST $ORPHEUS_BUILD
'''

[tasks.deploy]
quiet = true
description = "deploy latest static content"
depends = ['clean', 'build:lyre:release', 'lyre']
wait_for = ['update']
run = '''
scp -rq ./generated/* $ORPHEUS_HOST:$ORPHEUS_DIR
ssh $ORPHEUS_HOST $ORPHEUS_RESTART
'''
