[tools]
rust = "1.88.0"
watchexec = "2.3.2"
pandoc = "3.7.0.2"
yq = "4.46.1"
gum = "0.16.2"
node = "24.4.1"
npm = "11.4.2"
"npm:sass" = "1.89.2"

[hooks]
postinstall = '''
echo '> npm install'
npm install
'''
