#!/usr/bin/env bash

#MISE quiet=true
#MISE description="generate a new post from a template"

shopt -s nullglob
shopt -s globstar
set -e

function slugify {
    echo "$1" |
        iconv -t ascii//TRANSLIT |
        tr '[:upper:]' '[:lower:]' |
        sed -r \
            -e "s/[.\']+//g" \
            -e "s/[^[:alnum:]]+/-/g" \
            -e "s/^-+|-+$//g" \
            -e "s/-$//g"
}

function pink {
    gum style --foreground 212 "$1"
}

title=$(
    gum input \
        --header="What is the title of the post?"
)
if [ "$title" = "" ]; then
    echo "Title can't be blank"
    exit 0
fi
title_slug=$(slugify "$title")

exists=$(compgen -G "content/posts/**/$title_slug.md") || true
if [ "$exists" ]; then
    echo "A post titled \"$title\" already exists at $exists"
    exit 0
fi

echo "$(pink "Title"): $title"

series=$(
    available_series=$(
        echo content/posts/**/*.md |
            xargs -n1 -P "$(nproc)" yq -fr '.series' |
            sort -u |
            grep -vE '^$|null'
    )
    options=$(echo -e "$(pink "No Series")\n$(pink "New Series")\n$available_series")

    gum choose \
        --header="What series does this post belong to?" \
        --no-strip-ansi \
        <<<"$options"
)
if [ "$series" = "New Series" ]; then
    series=$(gum input --header="What should the series be called?")
fi
if [ "$series" = "No Series" ]; then
    series=""
fi
if [ "$series" ]; then
    echo "$(pink "Series"): $series"
fi
series_slug=$(slugify "$series")

tags=$(
    available_tags=$(
        echo content/posts/**/*.md |
            xargs -n1 -P "$(nproc)" yq -fr '.tags[]' |
            sort -u
    )

    gum choose \
        --header="Select Tags:" \
        --no-limit \
        --output-delimiter=" " \
        <<<"$available_tags"
)
if [ "$tags" ]; then
    echo "$(pink "Tags"): ${tags// /, }"
fi

template=$(
    printf '%s\n' content/templates/**/*.md |
        sed -e "s/^content\/templates\///" -e "s/.md$//" |
        gum choose \
            --header="Select a template"
)
echo "$(pink "Template"): $template"
template_path="content/templates/$template.md"

gum confirm || exit 0

printf -v published '%(%Y-%m-%d)T' -1

frontmatter=$(
    export title
    export published
    export series
    export tags
    yq -n '''
    .title = env(title) |
    .tagline = "" |
    .tagline tag="!!null" |
    .published = env(published) |
    (select(strenv(series) != "") | .series) = strenv(series) |
    (select(strenv(tags) != "") | .tags) = (env(tags) | split(" "))
    '''
)

md_dir="content/posts/${series:+"$series_slug/"}"
md_file="$md_dir$title_slug.md"
mkdir -p "$md_dir"

echo -e "---\n$frontmatter\n---\n\n$(cat "$template_path")" >"$md_file"

echo "Created $md_file"

if command -v code >/dev/null 2>&1; then
    code -r "$md_file"
fi
