[package]
name = "lyre"
version = "0.1.0"
edition = "2021"
description = "Orpheus companion tool -- manages, generates, and builds content"

[dependencies]
serde_yaml = "0.9.34"
verse = { path = "../verse" }
glob = "0.3.2"
tantivy = "0.24.2"
