#!/usr/bin/env bash

#MISE hide=true
#MISE quiet=true
#MISE depends=['build:lyre', 'render:posts']
#MISE wait_for=['clean']
#MISE sources=['content/posts/**/*.md']
#MISE outputs=['generated/posts/index/*']

mkdir -p generated/posts/index

if [ -e ./target/release/lyre ]; then
    ./target/release/lyre
else
    ./target/debug/lyre
fi
