#!/usr/bin/env bash

#MISE hide=true
#MISE quiet=true
#MISE wait_for=['clean']
#MISE sources=['content/web/main.js', 'node_modules/**/*.min.js']
#MISE outputs=['generated/static/*.js']

shopt -s globstar

mkdir -p generated/static/
cp node_modules/**/*.min.js generated/static/
cp content/web/main.js generated/static/
