#!/usr/bin/env bash

#MISE description="run a hot-reloading server in release mode"
#MISE depends=['build:release']

export ORPHEUS_OPTIONS="live_reload,no_cache"

mise watch --quiet --clear --restart gen ::: serve:release || true
