name: Checks
on: push
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: jdx/mise-action@v3
        with:
          experimental: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.rustup/toolchains/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - run: |
          mise run --prefix build
          mise run 'render:*'
          timeout 3 .mise/tasks/serve/_default || ret_val=$?
          if (($ret_val == 124)); then
              echo successfully ran for 3 seconds
              exit 0
          else
              exit 1
          fi
