name: Checks
on: push
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
      - run: |
          mise run --jobs 1 --prefix build ::: 'render:*'
          timeout 3 ./mise-tasks/serve/release || ret_val=$?
          if (($ret_val == 124)); then
              echo successfully ran for 3 seconds
              exit 0
          else
              exit 1
          fi