name: Checks
on: push
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - uses: Swatinem/rust-cache@v2
      - run: |
          mise run 'render:*'
