name: Mise Bump Tools
on:
  schedule:
    - cron: "0 6 * * 6" # 6am every Saturday
jobs:
  mise-bump:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.DROWRIN_BOT_APP_ID }}
          private-key: ${{ secrets.DROWRIN_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          experimental: true
      - id: bump_check
        run: |
          would_bump=$(mise upgrade --bump --dry-run | awk -F' in ' '{print $1}')
          {
            echo 'would_bump<<EOF'
            echo "$would_bump"
            echo EOF
          } >> "$GITHUB_OUTPUT"
      - run: mise upgrade --bump
      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: bump mise tool versions
          branch: bump-mise-tools
          delete-branch: true
          title: Bump mise tool versions
          body: ${{ steps.bump_check.outputs.would_bump }}
          labels: dependencies
