#!/usr/bin/env bash

#MISE description="run in debug mode"
#MISE depends=['build', 'gen']

export ORPHEUS_OPTIONS="live_reload,no_cache,simulate_lag"

echo "http://localhost:8000/"
./target/debug/orpheus || true
